# Generated by Django 2.0.13 on 2019-05-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome evento')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione evento')),
                ('place', models.CharField(max_length=100, verbose_name='Luogo')),
                ('date', models.DateField()),
                ('initHour', models.TimeField(blank=True, verbose_name='Ora di inizio')),
                ('endHour', models.TimeField(blank=True, verbose_name='Ora di fine')),
            ],
        ),
    ]
