# Generated by Django 2.2.7 on 2019-12-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endHour',
        ),
    ]
