# Generated by Django 2.2.7 on 2019-12-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_endhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.TextField(blank=True, verbose_name='Tipo di evento'),
        ),
    ]
