# Generated by Django 2.2.7 on 2019-12-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_event'),
        ('event', '0003_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='Creatore evento'),
        ),
    ]
