# Generated by Django 3.0.2 on 2020-01-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.IntegerField(default=1, verbose_name='Id per il get')),
                ('id_user', models.IntegerField(default=0, verbose_name='Max id utenti')),
                ('id_invite', models.IntegerField(default=0, verbose_name='Max id inviti')),
                ('id_event', models.IntegerField(default=0, verbose_name='Max id eventi')),
            ],
        ),
    ]
