# Generated by Django 2.0.13 on 2019-05-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(default='2012-10-22'),
        ),
    ]
