# Generated by Django 2.2.7 on 2019-11-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20190512_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.TextField(verbose_name='Descrizione della storia'),
        ),
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome della storia'),
        ),
    ]
