# Generated by Django 2.0.13 on 2019-05-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20190512_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(blank=True, verbose_name='Data'),
        ),
    ]
