# Generated by Django 2.2.7 on 2020-01-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20191130_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='img',
            field=models.TextField(blank=True, default='https://i.ibb.co/TMprtqM/67ee3aa7c384106968915f1288586505.png', verbose_name='Url immagine'),
        ),
    ]
