# Generated by Django 2.2.7 on 2020-01-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_history_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='img',
            field=models.TextField(blank=True, default='http://localhost:8000/static/image/casadario/history/history-default.png', verbose_name='Url immagine'),
        ),
    ]
