# Generated by Django 2.2.7 on 2020-01-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20200104_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='img',
            field=models.TextField(blank=True, default='https://polar-tundra-64747.herokuapp.com/static/image/casadario/history/history-default.png', verbose_name='Url immagine'),
        ),
    ]
