# Generated by Django 2.0.13 on 2019-05-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name="Nome dell'evento")),
                ('body', models.TextField(verbose_name="Descrizione dell'evento")),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
