# Generated by Django 2.0.13 on 2019-05-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didyouknow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curiosity',
            name='curiosityText',
            field=models.TextField(unique=True, verbose_name='Curiosity text'),
        ),
    ]
