# Generated by Django 3.0.2 on 2020-01-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didyouknow', '0002_auto_20190512_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curiosity',
            name='curiosityText',
            field=models.TextField(max_length=200, unique=True, verbose_name='Curiosity text'),
        ),
    ]
