# Generated by Django 2.0.13 on 2019-05-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterteinment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrizione')),
            ],
        ),
        migrations.CreateModel(
            name='EnterteinmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='Tipo di intrattenimento')),
            ],
        ),
        migrations.AddField(
            model_name='enterteinment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.EnterteinmentType'),
        ),
    ]
