# Generated by Django 2.0.13 on 2019-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterteinment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrizione'),
        ),
    ]
