# Generated by Django 2.0.13 on 2019-05-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=50,
                                          verbose_name='Nome evento')),
                ('description', models.TextField(
                    verbose_name='Descrizione evento')),
                ('place', models.CharField(max_length=100, verbose_name='Luogo')),
                ('date', models.DateField()),
                ('initHour', models.TimeField(
                    blank=True, verbose_name='Ora di inizio')),
                ('endHour', models.TimeField(verbose_name='Ora di fine')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gayPoint',
            field=models.IntegerField(default=0, verbose_name='Punti gay'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthPoint',
            field=models.IntegerField(
                default=0, verbose_name='Presenze questo mese'),
        ),
        migrations.AddField(
            model_name='user',
            name='totalPoint',
            field=models.IntegerField(
                default=0, verbose_name='Presenze totali'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(
                max_length=50, unique=True, verbose_name='User name'),
        ),
    ]
