# Generated by Django 2.0.13 on 2019-05-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190506_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
