# Generated by Django 2.2.7 on 2019-12-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Descrizione utente'),
        ),
    ]
