# Generated by Django 2.2.7 on 2020-01-03 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
