# Generated by Django 2.2.7 on 2020-01-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_lastdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImg',
            field=models.ImageField(blank=True, default='upload/single_user.png', upload_to='upload', verbose_name='Immagine profilo'),
        ),
    ]
