# Generated by Django 2.2.7 on 2020-01-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profileImg',
        ),
    ]
