# Generated by Django 2.2.7 on 2020-01-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImg',
            field=models.TextField(blank=True, default='https://i.ibb.co/vPgmQyf/single-user.png', verbose_name='Url immagine Profilo'),
        ),
    ]
