# Generated by Django 2.2.7 on 2020-01-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=models.TextField(blank=True, default='http://localhost:8000/static/image/casadario/profile/profile-default.png', verbose_name='Url immagine Profilo'),
        ),
    ]
