# Generated by Django 2.2.7 on 2020-01-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200104_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=models.TextField(blank=True, default='https://polar-tundra-64747.herokuapp.com/static/image/casadario/profile/profile-default.png', verbose_name='Url immagine Profilo'),
        ),
    ]
