# Generated by Django 3.0.2 on 2020-01-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200104_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
