# Generated by Django 2.2.7 on 2019-11-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banlist',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='banlist',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Cognome'),
        ),
    ]
